### ISSUE TITLE
non-implicit macro is descending where it shouldn't

### ISSUE THREAD

**Issue by fommil** [propensive/magnolia#119]
I have created a magnolia deriver for pureconfig https://github.com/pureconfig/pureconfig/issues/396#issuecomment-410233339

Unless I special case the value class (which I don't want to do!) then the following data structure will derive the `ServiceName` 

```scala
@deriving(ConfigReader)
final case class LoggingConfig(serviceName: ServiceName)

final case class ServiceName(value: String) extends AnyVal
```

Whereas I expect a compile time error reporting a missing `ConfigReader[ServiceName]`. The user can then choose to use `@deriving` or `@xderiving` on `ServiceName`, the former treating it as a product, the latter using the typeclass's definition of `xmap`. I don't want magnolia deciding to special case `AnyVal` for me as there is a choice to be made by the user and this leads to typeclass decoherence.

**Comment by fommil** [comment]
I have seen evidence of this descending into an `Option[A]`, i.e. that isn't an `AnyVal`, which is not good. It means magnolia currently doesn't support semiauto.

**Comment by fommil** [comment]
enabling debug I'm seeing trees like this expanded

```
[info]     val paramTypeclass$macro$13 = {
[info]       val servicenameTypeclass$macro$8 = {
[info]         val paramTypeclass$macro$10 = magnolia.examples.SemiDefault.string;
[info]         val parameters$macro$11: scala.Array[magnolia.Param[magnolia.examples.SemiDefault.Typeclass, magnolia.tests.ServiceName]] = new scala.Array(1);
[info]         parameters$macro$11.update(0, magnolia.Magnolia.param[magnolia.examples.SemiDefault.Typeclass, magnolia.tests.ServiceName, String]("value", false, paramTypeclass$macro$10, scala.None, ((x$55) => x$55.value), scala.Array()));
[info]         val typeName$macro$9 = magnolia.TypeName("magnolia.tests", "ServiceName");
[info]         magnolia.examples.SemiDefault.combine(magnolia.Magnolia.caseClass[magnolia.examples.SemiDefault.Typeclass, magnolia.tests.ServiceName](typeName$macro$9, false, true, parameters$macro$11, scala.Array(), ((fieldValues$macro$12: scala.Seq[_root_.scala.Any]) => {
[info]           if (fieldValues$macro$12.lengthCompare(parameters$macro$11.length).!=(0))
[info]             {
[info]               val msg = "`".+(typeName$macro$9.full).+("` has ").+(parameters$macro$11.length).+(" fields, not ").+(fieldValues$macro$12.size);
[info]               throw new java.lang.IllegalArgumentException(msg)
[info]             }
[info]           else
[info]             ();
[info]           new magnolia.tests.ServiceName(fieldValues$macro$12(0).asInstanceOf[String])
[info]         })))
[info]       };
[info]       servicenameTypeclass$macro$8
[info]     };
```

that shouldn't be getting created.

**Comment by fommil** [comment]
@joroKr21 any thoughts? Looks like you've made some edits around `directInferImplicit`. It's not supposed to recurse if the materialiser is not `implicit`

**Comment by joroKr21** [comment]
As far as I can remember this was by design. It's not assuming "full auto" in the sense that when the macro is not implicit you still have to call `implicit val foo: Foo[Bar] = deriveFoo[Bar]`. But then you can distinguish between "shallow" derivation - i.e. only derive one level of a case class hierarchy vs "deep" derivation - derive as much as possible. Magnolia has done the latter since inception (after all one of the goals was to show nice error messages when something fails deep withing the hierarchy). I haven't changed that. @propensive can correct me if I'm wrong.

Seeing derivation for `Option` is not impossible - after all it's just a trivial ADT.

But where do you see problems with typeclass coherence? The user should still be able to make any choices they want by implementing the instance in `ServiceName` and it should always take precedence. I'm not sure if that currently happens, but IMHO it's definitely the desired behavior (i.e. generated code should never trump hand-written code).

**Comment by fommil** [comment]
The main problem is that things get derived that you don't expect to get derived, if you live in a semiauto world. e.g. this `Option` derivation causes runtime failures in my app because there wasn't a deriver for Option and that broke the expected runtime formats. Similarly, AnyVals were getting auto derived instead of alerting me that they were missing.

In any case, I actually want "half auto" where the known subtypes of an ADT get derived, but not any other things. I think it's easy to support that, I'll send a PR and add more documentation.

**Comment by joroKr21** [comment]
That's the thing about expectations - they are subjective :smile: 

I think it's useful to have all three modes of derivation: "full auto", "deep semiauto" and "shallow semiauto", I'm just not sure what's the best way to achieve that - different macros, annotations (please no) or the implicit flat as you already did?
