### ISSUE TITLE
[Circe] Unclear implicit prioritisation rules

### ISSUE THREAD

**Issue by vpavkin** [propensive/magnolia#89]
Reproduction:
https://github.com/vpavkin/magnolia/blob/e278256e713ddf3b1aa3365898e930eff168274b/tests/src/main/scala/PriorityIssueTest.scala

Magnolia derivers sometimes override default instances, available from companion. For example, for this type

```scala
case class MapContainer(theMap: Map[String, List[Int]])
```
magnolia will derive coproduct codec for the `List` on rhs of the `Map`.

This only happens, when default instances are provided by means of being located in companion. If we import them explicitly (with `import io.circe.Encoder._`), then magnolia starts to see them.

This is confusing, and hard to notice and debug within deeply nested hierarchies.

**Comment by joroKr21** [comment]
In the test you import `import MagnoliaEncoder.genEncoder` which gives it higher priority than implicits in the companion `object Encoder` according to the regular implicit resolution rules in Scala. Even if we try to change it (which I'm not sure is possible), the net result will probably still be confusing because then people will be surprised why it doesn't follow the standard rules.

**Comment by vpavkin** [comment]
@joroKr21 makes sense, but when using circe `auto` we do kinda the same:

```
import io.circe.generic.auto._
```

And it doesn't stay in the way of default codecs.

Although, I have to admit, circe does some tricks with `Exported`, from end-user perspective it looks the same.

**Comment by joroKr21** [comment]
Sure, but there is also `generic.semiauto` which is arguably more useful. I guess the problem here is that you would want to support both use cases.

**Comment by vpavkin** [comment]
Closing in favor of #107
